In [1]:
import yaml
import modern_robotics as mr
from numpy import *
from numpy import array as a, r_ as r
import quad_functions
# read config file
with open("../configs/V2.yaml", "r") as f:
    conf = yaml.load(f, Loader=yaml.SafeLoader)

leg, m0 = quad_functions.parse_yaml(conf)

Slist1, Blist1, Mlist1, M1, Glist1, llist = leg(1)
Mlistinv1 = a([mr.TransInv(Mlist1[-1]), mr.TransInv(Mlist1[-2]),
               mr.TransInv(Mlist1[-3]), mr.TransInv(Mlist1[-4])])

In [2]:
import tests
tests.test_fk(Slist1, Blist1, Mlist1, M1, Glist1, llist)
# for _ in range(5):
#   tests.test_ik(Slist1, Blist1, Mlist1, M1, Glist1, llist)

In [3]:

# assert array_equal(Blist1, Blist1_check)


# def invertTransformationMatrices(Mlist):
#     Mlistinv = []
#     for M in Mlist:
#         Mlistinv.append(mr.TransInv(M))
#     return a(Mlistinv)


# def J(n, theta_list):
#     return mr.JacobianSpace(leg(n)[0], theta_list)


# test with some random angles
# for i in range(1, 5):
#     theta_list = random.rand(3)*2*pi-pi
#     p10_14_mr = mr.FKinSpace(M03, Slist, theta_list)[0:3, 3]+f_offset
#     p10_14_quad = quad_functions.fk(theta_list, l)
#     # assert allclose(p10_14_mr, p10_14_quad)


# for i in range(1, 5):
#     theta_list = random.rand(3)*2*pi-pi
#     p10_14_quad = quad_functions.fk(theta_list, l)
#     T10_14_quad = mr.RpToTrans([[1, 0, 0], [0, 1, 0], [0, 0, 1]], p10_14_quad)
#     thetalist0 = a([pi/2, pi/4, pi/4])
#     theta_list_quad = quad_functions.ik(p10_14_quad, l)
#     theta_list_mr, success = quad_functions.IKinSpace(
#         Slist, M03, T10_14_quad, thetalist0, 1e-6)
#     # print(theta_list, theta_list_quad, (theta_list_mr, success))
#     # print(p10_14_quad)
#     # assert allclose(theta_list, theta_list_quad)


thetalist = a([0, 0, 0])
thetadlist = a([0, 0, 0])
dthetadlist = a([0, 0, 0])
g = a([0, 0, -9.8])
Ftip = a([0, 0, 0, 0, 0, -9.8*m0/4])
# M01 = a([[1, 0, 0,        0],
#          [0, 1, 0,        0],
#          [0, 0, 1, 0.089159],
#          [0, 0, 0,        1]])
# M12 = a([[0, 0, 1,    0.28],
#          [0, 1, 0, 0.13585],
#          [-1, 0, 0,       0],
#          [0, 0, 0,       1]])
# M23 = a([[1, 0, 0,       0],
#          [0, 1, 0, -0.1197],
#          [0, 0, 1,   0.395],
#          [0, 0, 0,       1]])
# M34 = a([[1, 0, 0,       0],
#          [0, 1, 0,       0],
#          [0, 0, 1, 0.14225],
#          [0, 0, 0,       1]])
# G1 = diag([0.010267, 0.010267, 0.00666, 3.7, 3.7, 3.7])
# G2 = diag([0.22689, 0.22689, 0.0151074, 8.393, 8.393, 8.393])
# G3 = diag([0.0494433, 0.0494433, 0.004095, 2.275, 2.275, 2.275])
# Glist = a([G1, G2, G3])
# Mlist = a([M01, M12, M23, M34])
# Slist = a([[1, 0, 1,      0, 1,     0],
#            [0, 1, 0, -0.089, 0,     0],
#            [0, 1, 0, -0.089, 0, 0.425]]).T


# display(mr.InverseDynamics(
#     flip(thetalist), thetadlist, dthetadlist,
#     g, Ftip,
#     flip(invertTransformationMatrices(Mlist)), flip(Glist), flip(Slist.T).T
# ))
# display(mr.InverseDynamics(
#     flip(thetalist), flip(thetadlist), flip(dthetadlist),
#     0*g, -Ftip,
#     Mlistinv1, flip(Glist1), flip(Slist1)
# ))

display(mr.InverseDynamics(
    thetalist, thetadlist, dthetadlist,
    g, Ftip,
    Mlist1, Glist1, Slist1
))


display(quad_functions.IKinSpace3D(Slist1, M1, array(
    [0, 0, 0.25]), array([0.0, 0.0, 0.0]),  ev=0.01))

array([-4.22625,  0.     ,  7.35   ])

[[1.    0.    0.    0.   ]
 [0.    1.    0.    0.115]
 [0.    0.    1.    0.   ]
 [0.    0.    0.    1.   ]]
[0.13693553 0.115      0.18979692] [ 0.    -0.115  0.25 ]
[0.04641082 0.115      0.12810294] [-0.13693553 -0.115       0.06020308]
[0.09440568 0.115      0.16985241] [-0.04641082 -0.115       0.12189706]
[0.06433099 0.115      0.14694869] [-0.09440568 -0.115       0.08014759]
[0.08179644 0.115      0.1613317 ] [-0.06433099 -0.115       0.10305131]
[0.07112491 0.115      0.15294186] [-0.08179644 -0.115       0.0886683 ]
[0.07746414 0.115      0.15806632] [-0.07112491 -0.115       0.09705814]
[0.07363139 0.115      0.15501927] [-0.07746414 -0.115       0.09193368]
[0.07592491 0.115      0.156861  ] [-0.07363139 -0.115       0.09498073]
[0.0745438 0.115     0.1557586] [-0.07592491 -0.115       0.093139  ]
[0.07537237 0.115      0.15642236] [-0.0745438 -0.115      0.0942414]
[0.07487416 0.115      0.15602411] [-0.07537237 -0.115       0.09357764]
[0.07517332 0.115      0.15626356] [

(array([ 0.        ,  0.89603507, -0.89603507]), False)

In [4]:
%matplotlib qt

import plot_robot
plot_robot.plot_init()
plot_robot.plot_robot(Mlist, Glist, Slist)
plot_robot.fig.show()
# plot_robot.fig.clf()

NameError: name 'Mlist' is not defined

In [ ]:
# from matplotlib import pyplot as plt
# phi = linspace(0, 2*pi, 100)

# foot_pos = quad_functions.p(phi, 0.5, 0.25, [-0.06, 0.08], [-1.5e-2, 4.0e-2])
# plt.plot(foot_pos[0], foot_pos[2])
# plt.gca().invert_yaxis()

In [ ]:
def isStable(K): return all(K > 0)


p1 = a([xd(1)*lx0, yd(1)*ly0, 0])
p2 = a([xd(2)*lx0, yd(2)*ly0, 0])
p3 = a([xd(3)*lx0, yd(3)*ly0, 0])
p4 = a([xd(4)*lx0, yd(4)*ly0, 0])

S13 = quad_functions.ScrewFromPoints(p1, p3)
S34 = quad_functions.ScrewFromPoints(p3, p4)
S42 = quad_functions.ScrewFromPoints(p4, p2)
S21 = quad_functions.ScrewFromPoints(p2, p1)

S23 = quad_functions.ScrewFromPoints(p2, p3)
S41 = quad_functions.ScrewFromPoints(p4, p1)
S14 = quad_functions.ScrewFromPoints(p1, p4)
S32 = quad_functions.ScrewFromPoints(p3, p2)

F = -a([0, 0, -1, -.01, 0, 0])

chassis_boundary = a([S13, S34, S42, S21]).T
Kall = quad_functions.NormalizedVirtualPower(chassis_boundary, F)
up_1 = a([S34, S42, S23]).T
up_2 = a([S13, S34, S41]).T
up_3 = a([S14, S42, S21]).T
up_4 = a([S13, S32, S21]).T
K1 = quad_functions.NormalizedVirtualPower(up_1, F)
K2 = quad_functions.NormalizedVirtualPower(up_2, F)
K3 = quad_functions.NormalizedVirtualPower(up_3, F)
K4 = quad_functions.NormalizedVirtualPower(up_4, F)
display(all(K1 > 0), K1.min())
display(all(K2 > 0), K2.min())
display(all(K3 > 0), K3.min())
display(all(K4 > 0), K4.min())

np.False_

np.float64(-0.00975057824498499)

np.True_

np.float64(0.00975057824498499)

np.False_

np.float64(-0.00975057824498499)

np.True_

np.float64(0.00975057824498499)

In [ ]:
p1, p2, S21

(array([0.31559532, 0.0718385 , 0.        ]),
 array([ 0.31559532, -0.0718385 ,  0.        ]),
 array([0.        , 1.        , 0.        , 0.        , 0.        ,
        0.31559532]))

In [ ]:
chassis_boundary

array([[-1.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        , -1.        ,  0.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.0718385 ,  0.31559532,  0.0718385 ,  0.31559532]])